ifndef ARCH
ARCH=i686-linux
endif

include ../../config.make
DISTDIR = $(JMAXROOTDIR)/fts

PACKAGEROOT = ..
PACKAGELIB=$(LIBDIR)/lib$(PNAME).so
include $(JMAXDISTDIR)/Makefiles/Makefile.package
LDSOFLAGS += -L/usr/X11R6/lib -lX11 -lXext -lm

ARCH_CFLAGS += -Wall -Wno-unused
ARCH_CFLAGS += -fno-unroll-all-loops -funroll-loops -g

