#!/bin/bash
#
#  a script i wrote to automate restarting of jmax and a few other jobs.
#  only written for myself.
#

#INST=/opt/jmax
INST=/opt
#INST=/usr
ARCH=i686-linux
JMAKE="make ARCH=$ARCH"
INST2=$INST/lib/jmax/fts/bin/$ARCH/opt/fts
SAM=/home/projects/gridflow/samples

# SRC='array.[ch] video.c'
# SRC='grid.c grid_protocol.[ch] video.[ch] macros.h vout*.c vin*.c'
# SRC='grid_basic.c grid.c grid.h index.c tuple.c'
SRC='video_out.c grid_basic.c grid.c grid.h'

FILE=../mexico/bbb_main.jmax
#FILE=outside/grid_tcp.jmax
#FILE=outside/scale_test_2.jmax

FILE=$SAM/$FILE

#export DISPLAY=:1
ulimit -c unlimited

case $1 in
	edit) (nedit $SRC &) ;;
	kill) killall -9 java fts ;;
	run)  killall -9 java fts; jmax $FILE ;;
	run2)  (cd /opt/mexico; killall -9 java fts
		jmax $FILE /home/projects/gridflow/gf_control.jmax) ;;
	rund)
		killall -9 java fts
		jmax -jmaxConnection udpclient -jmaxMode debug \
			-jmaxPort 4242 $FILE
		echo run udp 127.0.0.1:4242 > /tmp/jmax-debug
		gdb $INST2 --command=/tmp/jmax-debug
	;;
	rundd)
		killall -9 java fts
		jmax -jmaxConnection udpclient -jmaxPort 4242 $FILE
#		echo press enter to continue
#		read foo
#		echo $INST2 udp 127.0.0.1:4242
		echo --------
		echo run udp 127.0.0.1:4242
		echo --------
		echo $INST2
		gdb $INST2
	;;
	core)
		gdb $INST2 core
	;;
	#install) $JMAKE && (cd ../../../../; $JMAKE install) ;;
	install) $JMAKE && (cd ../../; $JMAKE install) ;;
	clean)
		$JMAKE clean
		rm err err2 core
	;;
	cc) $JMAKE &> err
		cat err \
		| fgrep -v 'pasting would' \
		| fgrep -v '../../../../fts/src' \
		> err2
		pico err ;;
#		pico err2 ;;
	*|compile) $JMAKE ;;
#	*) echo "usage: ./t [edit|install]" ;;
esac


