#ifndef _LTILINCONFIG_H_
#define _LTILINCONFIG_H_
/* ../src/basics/config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to dummy `main' function (if any) required to link to the Fortran
   libraries. */
/* #undef F77_DUMMY_MAIN */

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
/* #undef F77_FUNC */

/* As F77_FUNC, but for C identifiers containing underscores. */
/* #undef F77_FUNC_ */

/* Define if F77 and FC dummy `main' functions are identical. */
/* #undef FC_DUMMY_MAIN_EQ_F77 */

/* define if processor has AMD 3DNow */
#define HAVE_3DNOW 1

/* define if processor has Altivec */
/* #undef HAVE_ALTIVEC */

/* Define if you have a BLAS library. */
/* #undef HAVE_BLAS */

/* Define to 1 if you have the `finite' function. */
#define HAVE_FINITE 1

/* defines if gtk libraries were found */
#define HAVE_GTK 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `isinf' function. */
#define HAVE_ISINF 1

/* Define to 1 if you have the `isnan' function. */
#define HAVE_ISNAN 1

/* Define if you have LAPACK library. */
/* #undef HAVE_LAPACK */

/* Define to 1 if you have the `jpeg' library (-ljpeg). */
#define HAVE_LIBJPEG 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `png' library (-lpng). */
#define HAVE_LIBPNG 1

/* Define to 1 if you have the `pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if you have the `z' library (-lz). */
#define HAVE_LIBZ 1

/* defines if the local implementation for png loader/savers was found */
#define HAVE_LOCALJPEG 1

/* defines if the local implementation for png loader/savers was found */
#define HAVE_LOCALPNG 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* define if the processor has intel mmx */
#define HAVE_MMX 1

/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES 

/* define if the unix/linux system has a /proc directory structure */
#define HAVE_PROC 1

/* define if processor has intel SSE */
/* #undef HAVE_SSE */

/* define if processor has intel SSE2 */
/* #undef HAVE_SSE2 */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* define if the std::streambuf has member fd() */
/* #undef HAVE_STREAMBUF_FD */

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* defines if the susan algorithms are present in the library */
#define HAVE_SUSAN 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `_finite' function. */
/* #undef HAVE__FINITE */

/* Define to 1 if you have the `_isinf' function. */
/* #undef HAVE__ISINF */

/* Define to 1 if you have the `_isnan' function. */
/* #undef HAVE__ISNAN */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "LTI-Lib"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "LTI-Lib 1.9.12"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "lti-lib"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.9.12"

/* define processor type */
#define PROCESSOR AMD Athlon(tm) Processor

/* define processor vendor */
#define PROCESSOR_VENDOR AuthenticAMD

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* define type for byte */
#define _LTI_BYTE char

/* define type for two-bytes */
#define _LTI_WORD16 short int

/* define type for four-bytes */
#define _LTI_WORD32 int

/* define type for eight-bytes */
#define _LTI_WORD64 long long

#endif
